export { default as Brand } from './Brand';
export { default as CareerAdvice } from './CareerAdvice';
export { default as Collection } from './Collection/Collection';
export { default as Discount } from './Discount';
export { default as Fashion } from './Fashion/Fashion';
export { default as FashionCard } from './Fashion/FashionCard';
export { default as Gift } from './Gift';
export { default as Hero } from './Hero';
export { default as ShopNow } from './ShopNow';
export * from './index';
